// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Login and obtain a JWT",
                "parameters": [{
                    "description": "Login payload",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"$ref": "#/definitions/httpadapter.LoginRequest"}
                }],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/httpadapter.AuthResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/httpadapter.ErrorResponse"}}
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Register a new user",
                "parameters": [{
                    "description": "Registration payload",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"$ref": "#/definitions/httpadapter.RegisterRequest"}
                }],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/httpadapter.UserResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/httpadapter.ErrorResponse"}},
                    "409": {"description": "Conflict", "schema": {"$ref": "#/definitions/httpadapter.ErrorResponse"}}
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "List users",
                "parameters": [
                    {"type": "integer", "default": 20, "name": "limit", "in": "query"},
                    {"type": "integer", "default": 0, "name": "offset", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/httpadapter.UserResponse"}}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/httpadapter.ErrorResponse"}}
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Get user by ID",
                "parameters": [{"type": "string", "name": "id", "in": "path", "required": true}],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/httpadapter.UserResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/httpadapter.ErrorResponse"}}
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Update a user",
                "parameters": [
                    {"type": "string", "name": "id", "in": "path", "required": true},
                    {"description": "Update payload", "name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/httpadapter.UpdateUserRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/httpadapter.UserResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/httpadapter.ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/httpadapter.ErrorResponse"}}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["users"],
                "summary": "Delete a user",
                "parameters": [{"type": "string", "name": "id", "in": "path", "required": true}],
                "responses": {
                    "204": {"description": "No Content"},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/httpadapter.ErrorResponse"}}
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": ["application/json"],
                "tags": ["health"],
                "summary": "Liveness probe",
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/httpadapter.HealthResponse"}}
                }
            }
        },
        "/readyz": {
            "get": {
                "produces": ["application/json"],
                "tags": ["health"],
                "summary": "Readiness probe",
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/httpadapter.HealthResponse"}},
                    "503": {"description": "Service Unavailable", "schema": {"$ref": "#/definitions/httpadapter.ErrorResponse"}}
                }
            }
        }
    },
    "definitions": {
        "httpadapter.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {"type": "string"},
                "user": {"$ref": "#/definitions/httpadapter.UserResponse"}
            }
        },
        "httpadapter.ErrorResponse": {
            "type": "object",
            "properties": {"error": {"type": "string", "example": "invalid input"}}
        },
        "httpadapter.HealthResponse": {
            "type": "object",
            "properties": {"status": {"type": "string", "example": "ok"}}
        },
        "httpadapter.LoginRequest": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email": {"type": "string", "example": "alice@example.com"},
                "password": {"type": "string", "example": "secret123"}
            }
        },
        "httpadapter.RegisterRequest": {
            "type": "object",
            "required": ["email", "name", "password"],
            "properties": {
                "email": {"type": "string", "example": "alice@example.com"},
                "name": {"type": "string", "example": "Alice"},
                "password": {"type": "string", "minLength": 8, "example": "secret123"}
            }
        },
        "httpadapter.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "email": {"type": "string", "example": "alice.new@example.com"},
                "name": {"type": "string", "example": "Alice Updated"}
            }
        },
        "httpadapter.UserResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "string", "example": "550e8400-e29b-41d4-a716-446655440000"},
                "email": {"type": "string", "example": "alice@example.com"},
                "name": {"type": "string", "example": "Alice"},
                "created_at": {"type": "string"},
                "updated_at": {"type": "string"}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go Hexagonal Starter API",
	Description:      "Production-ready Go microservice using Hexagonal Architecture.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
