sonar.projectKey=example_go-hexagonal-starter
sonar.organization=example
sonar.sources=.
sonar.exclusions=**/*_test.go,api/docs/**,bin/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
